# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
# It can also be set to "author"
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - dzbo
  - richtera
  - Hugoo
  - doubleppereira

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

skipKeywords:
  - chore(
