query collection(
  $address: String!
  $limit: Int
  $offset: Int
  $search: String
) {
  collection: Token(
    where: {
      _and: [
        { baseAsset_id: { _ilike: $address } }
        {
          _or: [
            { formattedTokenId: { _ilike: $search } }
            { tokenId: { _ilike: $search } }
          ]
        }
      ]
    }
    limit: $limit
    order_by: { tokenId: asc }
    offset: $offset
  ) {
    ...token
  }

  # use aggregate to count total number of tokens
  meta: Token_aggregate(
    where: {
      _and: [
        { baseAsset_id: { _ilike: $address } }
        {
          _or: [
            { formattedTokenId: { _ilike: $search } }
            { tokenId: { _ilike: $search } }
          ]
        }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
