query profileReceivedAssets($address: String!) {
  Profile(where: { id: { _ilike: $address } }) {
    receivedAssets {
      asset {
        ...asset
      }
    }

    holds {
      ...hold
    }
  }
}
