query profileAssets($address: String!) {
  profiles: Profile(where: { id: { _ilike: $address } }) {
    # TODO temporary use alias before index has the data
    lsp5ReceivedAssets: receivedAssets {
      asset {
        ...asset
      }
    }

    lsp12IssuedAssets {
      asset {
        ...asset
      }
    }

    holds {
      ...hold
    }
  }
}
