query profileShowcase {
  Profile(
    limit: 500
    where: {
      _and: [
        { profileImages: { url: { _is_null: false } } }
        { backgroundImages: { url: { _is_null: false } } }
        { name: { _is_null: false } }
        { name: { _neq: "" } }
      ]
    }
  ) {
    # ...profile
    name
    id
    backgroundImages(limit: 1) {
      url
      height
      width
    }
    profileImages(limit: 1) {
      width
      url
      height
    }
  }
}
