fragment profile on Profile {
  fullName
  description
  name
  id
  standard
  interfaces
  blockNumber
  links {
    title
    url
  }
  tags
  backgroundImages(order_by: { width: desc }) {
    url: src
    height
    width
    verified
  }
  profileImages(order_by: { width: desc }) {
    url: src
    width
    height
    verified
  }
  ...avatars
}
