query profileAssets($address: String!) {
  receivedAssets: ReceivedAsset(where: { profile_id: { _ilike: $address } }) {
    asset {
      ...asset # TODO optimize to use only necessary fields
    }
  }

  # TODO remove issuedAssets out when filters are done
  # TODO this is a fix for duplicates with extra where clause
  issuedAssets: IssuedAsset(
    where: {
      _and: [{ profile_id: { _ilike: $address } }, { id: { _nlike: "%-0x%" } }]
    }
  ) {
    id
    asset {
      ...asset
    }
  }

  # Side load holds to get balances
  holds: Hold(where: { profile_id: { _ilike: $address } }) {
    asset {
      id
      standard
    }
    token {
      tokenId
      baseAsset {
        id
        standard
      }
    }
    balance
  }
}
