query profileAssets($address: String!) {
  receivedAssets: ReceivedAsset(
    where: { profile_id: { _ilike: $address } }
    distinct_on: asset_id
  ) {
    asset {
      ...basicAsset
    }
  }

  issuedAssets: IssuedAsset(
    where: { profile_id: { _ilike: $address } }
    distinct_on: asset_id
  ) {
    id
    asset {
      ...basicAsset
    }
  }

  # Side load holds to get balances
  holds: Hold(where: { profile_id: { _ilike: $address } }) {
    asset {
      id
      standard
    }
    token {
      tokenId
      baseAsset {
        id
        standard
      }
      # we need to include images for case where user has only one token from collection since then we display token as asset
      images(order_by: { index: asc, width: desc }, limit: 1) {
        url: src
        width
        height
        index
        verified
        error
      }
    }
    balance
  }
}
