fragment token on Token {
  lsp4TokenName
  lsp4TokenSymbol
  baseAsset {
    ...asset
  }
  lsp4TokenType
  lsp8TokenIdFormat
  tokenId
  baseAsset {
    lsp8TokenMetadataBaseURI
  }

  # creators
  lsp4Creators {
    profile {
      ...creator
    }
  }

  # LSP4 metadata
  # name # TODO add this when in index
  description
  links {
    url
    title
  }
  images {
    url
    width
    height
  }
  icons {
    url
    width
    height
  }
  assets {
    fileType
    url
    contentAsset {
      id
    }
    contentToken {
      tokenId
      baseAsset {
        id
      }
    }
  }
  # attributes
}
